/*
 * Generated by MTK SP Drv_CodeGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Mon Sep 16 09:57:36 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


